{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 12, "max_value": 512, "step": 100, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer2", "default": null, "conditions": [], "min_value": 12, "max_value": 512, "step": 100, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer3", "default": null, "conditions": [], "min_value": 12, "max_value": 512, "step": 100, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"units": 12, "units_layer2": 12, "units_layer3": 12, "learning_rate": 0.0005011872336272724}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 264, in _run_and_update_trial\n    tuner_utils.convert_to_metrics_dict(\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 132, in convert_to_metrics_dict\n    [convert_to_metrics_dict(elem, objective) for elem in results]\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 132, in <listcomp>\n    [convert_to_metrics_dict(elem, objective) for elem in results]\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 145, in convert_to_metrics_dict\n    best_value, _ = _get_best_value_and_best_epoch_from_history(\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 116, in _get_best_value_and_best_epoch_from_history\n    objective_value = objective.get_value(metrics)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras_tuner/src/engine/objective.py\", line 59, in get_value\n    return logs[self.name]\nKeyError: 'val_mse'\n"}